### ISSUE TITLE
Any idea when this will released !

### ISSUE THREAD

**Issue by arungowtham** [pelias/tiger#1]
Hi folks, any estimate when this would be released for production usage?

**Comment by orangejulius** [comment]
Hey @arungowtham,
I don't believe any work will ever be done in this repository (we should probably move it to https://github.com/pelias-deprecated), however we recently completed support for TIGER in https://github.com/pelias/interpolation, so do check that out. Let us know in that repo if you have any questions!

**Comment by missinglink** [comment]
@arungowtham for example the query:
> http://search.mapzen.com/v1/search?text=220 5th st ne, paris, tx

will return an interpolated address value based off block range data imported from TIGER 2016

**Comment by arungowtham** [comment]
Hey @missinglink ,
I have a local instance of pelias running and lately i've been trying to know more about interpolation, but i see it's in beta stage and the pre-built databases aren't available yet, so once they are available i'll use them. Anyhow thanks for mentioning about interpolation :+1:
